name: drift_self_ref_table
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  drift: ^2.13.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.17

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  
flutter:
  uses-material-design: true